---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Budgets"
Parameters:
  NotificationEmail1:
    Type: String
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: Must be a valid email address.
    Description: Email address to notify budgets
Resources:
  Budget:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetName: "$100 Budget"
        BudgetLimit:
          Amount: 100
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
        CostTypes:
          IncludeCredit: true
      NotificationsWithSubscribers:
        # 50% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            # TODO: Discord notification via SNS
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            # TODO: Discord notification via SNS
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 80% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            # TODO: Discord notification via SNS
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            # TODO: Discord notification via SNS
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 100% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            # TODO: Discord notification via SNS
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            # TODO: Discord notification via SNS
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
