---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Budgets"
Parameters:
  NotificationEmail1:
    Type: String
    AllowedPattern: ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: Must be a valid email address.
    Description: Email address to notify budgets
Resources:
  # An SNS topic on Budget Alarms
  BudgetAlarmsSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: soar-budget-alarm

  # Allows aws budgets to publish to the SNS Topic
  BudgetAlarmsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
      - !Ref BudgetAlarmsSnsTopic
      PolicyDocument:
        Version: 2008-10-17
        Statement:
        - Sid: "Allow AWS Budgets to send to this topic"
          Effect: Allow
          Principal:
            Service: budgets.amazonaws.com
          Action: SNS:Publish
          Resource: !Ref BudgetAlarmsSnsTopic

  BudgetExcCredits:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetName: "$100 Budget (exc) Credits"
        BudgetLimit:
          Amount: 100
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
        CostTypes:
          IncludeCredit: false
      NotificationsWithSubscribers:
        # 10% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 10
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 10
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 20% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 20
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 20
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 50% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 80% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 100% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1

  BudgetIncCredits:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetName: "$100 Budget (inc) Credits"
        BudgetLimit:
          Amount: 100
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
        CostTypes:
          IncludeCredit: true
      NotificationsWithSubscribers:
        # 10% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 10
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 10
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 20% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 20
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 20
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 50% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 50
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 80% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        # 100% actual and forecasted
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 100
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: SNS
              Address: !Ref BudgetAlarmsSnsTopic
            - SubscriptionType: EMAIL
              Address: !Ref NotificationEmail1

Outputs:
  BudgetAlarmsSnsTopic:
    Description: "The SNS topic for the budget alarms"
    Value: !Ref BudgetAlarmsSnsTopic
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'BudgetAlarmsSnsTopic' ] ]

