AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Developer role in Sydney
Resources:
  DeveloperAccessManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: A managed policy only for developers
      ManagedPolicyName: DeveloperAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: DenyAdmin
          Effect: Deny
          Action:
          - organizations:*
          - account:*
          Resource: "*"
        - Sid: AllowS3
          Effect: Allow
          Action: s3:*
          Resource: "*"
        - Sid: AllowIam
          Effect: Allow
          Action: iam:*
          Resource: "*"
        - Sid: AllowEC2
          Effect: Allow
          Action: ec2:*
          Resource: "*"
          Condition:
            StringEquals:
              aws:RequestedRegion: ap-southeast-2
            StringEquals:
              ec2:Region: ap-southeast-2
        - Sid: AllowCFN
          Effect: Allow
          Action: cloudformation:*
          Resource: "*"
          Condition:
            StringEquals:
              aws:RequestedRegion: ap-southeast-2
        - Sid: AllowCloudwatch
          Effect: Allow
          Action: cloudwatch:*
          Resource: "*"
          Condition:
            StringEquals:
              aws:RequestedRegion: ap-southeast-2
        - Sid: AllowLambda
          Effect: Allow
          Action: lambda:*
          Resource: "*"
          Condition:
            StringEquals:
              aws:RequestedRegion: ap-southeast-2
        - Sid: AllowGuardDuty
          Effect: Allow
          Action: guardduty:*
          Resource: "*"
          Condition:
            StringEquals:
              aws:RequestedRegion: ap-southeast-2
  BillingViewAccessManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: View billing information
      ManagedPolicyName: BillingViewAccess
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ViewBilling
          Effect: Allow
          Action:
          - aws-portal:ViewPaymentMethods
          - aws-portal:ViewAccount
          - aws-portal:ViewBilling
          - aws-portal:ViewUsage
          Resource: "*"

Outputs:
  DeveloperAccessManagedPolicy:
    Description: DeveloperAccessManagedPolicy
    Value: !Ref DeveloperAccessManagedPolicy
    Export:
      Name: DeveloperAccessManagedPolicy
  BillingViewAccessManagedPolicy:
    Description: BillingViewAccessManagedPolicy
    Value: !Ref BillingViewAccessManagedPolicy
    Export:
      Name: BillingViewAccessManagedPolicy
