AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This defines the permission set for AWS SSO to be run in the master account.
  Should all users will have PowerUserAccess to Sydney region?
  This has not been run using CFN because what is instance sso arn?.
  Manually created for now.
Resources:
  PowerUserAccessSydney:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: PowerUserAccessPermissionSet
      Description: PowerUser
      InstanceArn: arn:aws:sso:::instance ??? what is this ??
      ManagedPolicies:
        - !ImportValue DeveloperManagedPolicy
