AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This defines the permission set for AWS SSO.
  All users will have PowerUserAccess only at the Sydney region.
  To be run in the master account.
  This has not been run using CFN because what is instance sso arn?.
  Manually created
Resources:
  PowerUserAccessSydney:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: PowerUserAccessPermissionSet
      Description: PowerUser
      InstanceArn: arn:aws:sso:::instance ??? WHAT IS THIS???
      InlinePolicy: |
        {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "NotAction": [
                    "iam:*",
                    "organizations:*",
                    "account:*"
                ],
                "Resource": "*"
            },
            {
                "Effect": "Allow",
                "Action": [
                    "iam:CreateServiceLinkedRole",
                    "iam:DeleteServiceLinkedRole",
                    "iam:ListRoles",
                    "organizations:DescribeOrganization",
                    "account:ListRegions"
                ],
                "Resource": "arn:aws:*:ap-southeast-2:*"
            }
        ]
        }
