AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets
Resources:
  DiscordAlertsChannelWebhook:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /discord/channel/alerts-webhook
      SecretString: CHANGE ME IN THE CONSOLE
  DiscordDevAlertsChannelWebhook:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /discord/channel/dev-alerts-webhook
      SecretString: CHANGE ME IN THE CONSOLE

Outputs:
  DiscordAlertsChannelWebook:
    Value: !Ref DiscordAlertsChannelWebhook
    Description: Alerts channel webhook
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'DiscordAlertsChannelWebhook' ] ]
  DiscordDevAlertsChannelWebook:
    Value: !Ref DiscordDevAlertsChannelWebhook
    Description: Dev channel webhook
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'DiscordDevAlertsChannelWebhook' ] ]
