---
AWSTemplateFormatVersion: '2010-09-09'
Description: The CICD for the SOAR services under /services

Mappings:
  Branch:
    us-east-1:
      qa: master
      prod: release

Parameters:
  AwsEnvironment:
    Type: String
    AllowedValues:
    - qa
    - prod

Resources:
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub:
        - "${AwsEnvironment}-comp9447-team4-code-pipeline-service-role"
        - AwsEnvironment: !Ref AwsEnvironment
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
            - cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/soar/"
      Policies:
      - PolicyName: soar-codepipeline-service-policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action:
            - s3:Put*
            - s3:List*
            - s3:Get*
            - s3:Create*
            Resource:
            - !GetAtt CodeBuildArtifactsBucket.Arn
            - !GetAtt LambdaArtifactsBucket.Arn
            - Fn::Sub:
                - "${bucket_arn}/*"
                - bucket_arn: !GetAtt CodeBuildArtifactsBucket.Arn
            - Fn::Sub:
                - "${bucket_arn}/*"
                - bucket_arn: !GetAtt LambdaArtifactsBucket.Arn
            Effect: Allow

          - Action:
            - s3:Create*
            - cloudtrail:*
            Resource: "*"
            Effect: Allow

          - Action:
            - elasticloadbalancing:*
            - autoscaling:*
            - cloudwatch:*
            - ecs:*
            - codebuild:*
            - codestar-connections:*
            - iam:PassRole
            Resource: "*"
            Effect: Allow
          - Action:
            - "iam:*"
            Effect: Allow
            Resource:
            - "*"
            # TODO Make any changes only to IAM that starts with soar
            #     - !Sub "arn:aws:iam::${AWS::AccountId}:role/soar"
            #     - !Sub "arn:aws:iam::${AWS::AccountId}:policy/soar"

          # TODO: make this more concentrated
          - Action:
            - "apigateway:*"
            Resource: "*"
            Effect: Allow

          # TODO: make this more concentrated
          - Action:
            - "lambda:*"
            Resource: "*"
            Effect: Allow

          - Action:
            - "iam:CreateServiceLinkedRole"
            Resource: "*"
            Effect: Allow
      # TODO: make this less permissive
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
      - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      - arn:aws:iam::aws:policy/AmazonSNSFullAccess
      - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/soar/"
      RoleName:
        Fn::Sub:
          - "${AwsEnvironment}-comp9447-team4-code-build-service-role"
          - AwsEnvironment: !Ref AwsEnvironment
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: "CodeBuildServicePolicy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            Resource: "*"
          - Effect: "Allow"
            Action:
            - "s3:PutObject"
            - "s3:GetObject"
            - "s3:GetObjectVersion"
            - "s3:ListBucket"
            Resource:
            - !GetAtt CodeBuildArtifactsBucket.Arn
            - !GetAtt LambdaArtifactsBucket.Arn
            - Fn::Sub:
                - "${bucket_arn}/*"
                - bucket_arn: !GetAtt CodeBuildArtifactsBucket.Arn
            - Fn::Sub:
                - "${bucket_arn}/*"
                - bucket_arn: !GetAtt LambdaArtifactsBucket.Arn
          - Effect: "Allow"
            Action:
            - "ecr:InitiateLayerUpload"
            - "ecr:GetAuthorizationToken"
            Resource: "*"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess

  # Where codebuild will place artifacts after builds (zip files)
  CodeBuildArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub:
        - "${AwsEnvironment}-comp9447-team4-codebuild-artifacts"
        - AwsEnvironment: !Ref AwsEnvironment
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
      LifecycleConfiguration:
        Rules:
        - Id: DeleteContentAfter7Days
          Status: 'Enabled'
          ExpirationInDays: 7

  # Lambda artifacts
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub:
        - "${AwsEnvironment}-comp9447-team4-lambda-artifacts"
        - AwsEnvironment: !Ref AwsEnvironment
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true
      LifecycleConfiguration:
        Rules:
        - Id: DeleteContentAfter7Days
          Status: 'Enabled'
          ExpirationInDays: 7

  # Allow codebuild and pipeline to access the bucket
  CodeBuildArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CodeBuildArtifactsBucket
      PolicyDocument:
        Statement:
        - Sid: WhitelistedGet
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt CodeBuildServiceRole.Arn
            - !GetAtt CodePipelineServiceRole.Arn
          Action:
          - s3:GetObject
          - s3:GetObjectVersion
          - s3:GetBucketVersioning
          Resource:
          - Fn::Sub:
            - 'arn:aws:s3:::${BucketName}/*'
            - BucketName: !Ref CodeBuildArtifactsBucket
          - Fn::Sub:
            - 'arn:aws:s3:::${BucketName}'
            - BucketName: !Ref CodeBuildArtifactsBucket
        - Sid: WhitelistedPut
          Effect: Allow
          Principal:
            AWS:
            - !GetAtt CodeBuildServiceRole.Arn
            - !GetAtt CodePipelineServiceRole.Arn
          Action: s3:PutObject
          Resource:
          - Fn::Sub:
            - 'arn:aws:s3:::${BucketName}/*'
            - BucketName: !Ref CodeBuildArtifactsBucket
          - Fn::Sub:
            - 'arn:aws:s3:::${BucketName}'
            - BucketName: !Ref CodeBuildArtifactsBucket

  # The CodeBuild definition of our soar services
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: SoarCodeBuildProject
      BadgeEnabled: true
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        PrivilegedMode: true
        EnvironmentVariables:
        - Name: AWS_ACCOUNT_ID
          Value: !Sub "${AWS::AccountId}"
        - Name: AWS_DEFAULT_REGION
          Value: !Sub "${AWS::Region}"
        - Name: AWS_ENVIRONMENT
          Value:
            Fn::Sub:
            - "${AwsEnvironment}"
            - AwsEnvironment: !Ref AwsEnvironment
        - Name: LAMBDA_ARTIFACTS_BUCKET
          Value: !Ref LambdaArtifactsBucket
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: GITHUB
        Location: https://github.com/comp9447-team4/soar
        BuildSpec: services/buildspec.yml
        ReportBuildStatus: true
        Auth:
          Type: OAUTH

  # The pipeline that gets triggered on master for qa
  # or release for prod
  # Assumes you have created a successful OAUTH connection to Github repo using CodeStar
  # See ./bin/codestar.sh
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: SoarServiceCICDPipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref CodeBuildArtifactsBucket
      Stages:
      # Pull from Github
      - Name: Source
        Actions:
        - InputArtifacts: []
          Name: Source
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: CodeStarSourceConnection
          OutputArtifacts:
          - Name: SourceArtifact
          Configuration:
            ConnectionArn: !ImportValue GithubRepoCodeStarConnectionArn
            BranchName: !FindInMap [Branch, !Ref "AWS::Region", !Ref AwsEnvironment ]
            FullRepositoryId: comp9447-team4/soar
          RunOrder: 1
      # Build the artifacts
      - Name: Build
        Actions:
        - Name: Build
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          InputArtifacts:
          - Name: SourceArtifact
          OutputArtifacts:
          - Name: BuildArtifact
          Configuration:
            ProjectName: SoarCodeBuildProject
          RunOrder: 1
      #########################
      # DEPLOYMENTS
      # https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CloudFormation.html
      #########################
        # HELLO WORLD
      - Name: Deploy
        Actions:
        - Name: DeployHelloWorld
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CloudFormation
          InputArtifacts:
          - Name: BuildArtifact
          Configuration:
            ActionMode: REPLACE_ON_FAILURE
            StackName: !Sub "${AwsEnvironment}-HelloWorld"
            TemplatePath: "BuildArtifact::services/hello-world/transformed.yaml"
            RoleArn: !GetAtt CodePipelineServiceRole.Arn
            Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
        # BUDGET ALARMS
        - Name: DeployBudgetAlarms
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CloudFormation
          InputArtifacts:
          - Name: BuildArtifact
          Configuration:
            ActionMode: REPLACE_ON_FAILURE
            StackName: !Sub "${AwsEnvironment}-BudgetAlarms"
            TemplatePath: "BuildArtifact::services/budget-alarms/transformed.yaml"
            RoleArn: !GetAtt CodePipelineServiceRole.Arn
            Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
        #  Code Pipeline Bot
        - Name: DeployCodePipelineBot
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CloudFormation
          InputArtifacts:
          - Name: BuildArtifact
          Configuration:
            ActionMode: REPLACE_ON_FAILURE
            StackName: !Sub "${AwsEnvironment}-CodePipelineBot"
            TemplatePath: "BuildArtifact::services/codepipeline-notifier/transformed.yaml"
            RoleArn: !GetAtt CodePipelineServiceRole.Arn
            Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
        #  S3ToEsForwarder
        - Name: DeployS3ToEsForwarder
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CloudFormation
          InputArtifacts:
          - Name: BuildArtifact
          Configuration:
            ActionMode: REPLACE_ON_FAILURE
            StackName: !Sub "${AwsEnvironment}-S3ToEsForwarder"
            TemplatePath: "BuildArtifact::services/s3-to-es-forwarder/transformed.yaml"
            RoleArn: !GetAtt CodePipelineServiceRole.Arn
            Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
            ParameterOverrides: !Sub >-
              {
                "AwsEnvironment":"${AwsEnvironment}"
              }
Outputs:
  CodeBuildArtifactsBucket:
    Value: !Ref CodeBuildArtifactsBucket
    Description: CodeBuildArtifactsBucket
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'CodeBuildArtifactsBucket' ] ]
  LambdaArtifactsBucket:
    Value: !Ref LambdaArtifactsBucket
    Description: Lambda artifacts bucket
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LambdaArtifactsBucket' ] ]