---
AWSTemplateFormatVersion: '2010-09-09'
Description: ElasticSearch

Mappings:
  Branch:
    us-east-1:
      qa: master
      prod: release

Parameters:
  AwsEnvironment:
    Type: String
    AllowedValues:
    - qa
    - prod

Resources:
  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !Sub "${AwsEnvironment}-comp9447-team4-es"
      ElasticSearchVersion: 5.1
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: "true"
        InstanceCount: "2"
        ZoneAwarenessEnabled: "true"
        # Free tier
        InstanceType: "t2.small.elasticsearch"
        DedicatedMasterType: "t2.small.elasticsearch"
        DedicatedMasterCount: "3"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      SnapshotOptions:
        AutomatedSnapshotStartHour: "0"
      CognitoOptions:
        Enabled: true
        IdentityPoolId: !Ref CognitoIdentityPool

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AwsEnvironment}_es_user_pool"

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "qa_es_identity_pool"
      # https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-cognito-auth.html
      # you must allow unauthenticated then ES unsets it for you
      AllowUnauthenticatedIdentities: true
Outputs:
  UserPoolUrl:
    Value: !GetAtt CognitoUserPool.ProviderURL
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'UserPoolUrl' ] ]

#AccessPolicies:
#  Version: "2012-10-17"
#  Statement:
#  - Effect: "Allow"
#    Sid: "AllowDevRole"
#    Principal:
#      # AWS: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-reserved/sso.amazonaws.com/ap-southeast-2/AWSReservedSSO_DeveloperAccess*"
#      AWS: !Sub "arn:aws:iam::${AWS::AccountId}:role/*"
#    Action: "es:*"
#    # - "es:Get*"
#    # - "es:List*"
#    # - "es:Describe*"
#    # - "es:HttpGet*"
#    # - "es:ESHttpGet"
#    # - "es:ESHttpPost"
#    # - "es:ESHttpPut"
#    # - "es:ESHttpHead"
#    # - "es:ESHttpPatch"
#    # # Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${AwsEnvironment}-comp9447-team4-es/*"
#    Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*"
