version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis-waf-logging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ei1wdt2g2rw4"
s3_prefix = "kinesis-waf-logging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KinesisBufferIntervalSeconds=\"900\" KinesisBufferSizeMB=\"3\""
