version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "waf-apigateway"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tbxmul61l44z"
s3_prefix = "waf-apigateway"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "ActivateSqlInjectionProtectionParam=\"yes\" ActivateCrossSiteScriptingProtectionParam=\"yes\" ActivateHttpFloodProtectionParam=\"yes - AWS WAF rate based rule\" ActivateScannersProbesProtectionParam=\"no\" ActivateReputationListsProtectionParam=\"no\" ActivateBadBotProtectionParam=\"no\" EndpointType=\"ALB\" AppAccessLogBucket=\"api-accesslog-waf\" RequestThreshold=\"100\" ErrorThreshold=\"50\" WAFBlockPeriod=\"240\" KeepDataInOriginalS3Location=\"No\""
