version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Checking versions of build dependencies"
      - jq --version
      - pip --version
      - sam --version

  build:
    commands:
    # Get the artifacts bucket for lambdas
    - echo "Got the lambda artifacts bucket: ${LAMBDA_ARTIFACTS_BUCKET}"
    # Build Hello World
    - cd services/hello-world/
    - rm *.toml
    - >-
      sam package
      --template-file ./template.yml
      --output-template-file ./transformed.yml
      --s3-bucket "${LAMBDA_ARTIFACTS_BUCKET}"
    - cd -
    # TODO: Build more artifacts here

  post_build:
    commands:
    - echo "Completed SOAR service build on `date`"

artifacts:
  files:
  - ./services/hello-world/transformed.yml
