version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo "Checking versions of build dependencies"
      - jq --version
      - pip --version
      - sam --version

  # AWS SAM defaults to read template.yaml with an A!
  build:
    commands:
      - pwd
      # HelloWorld
      - cd services/hello-world/
      - sam build
      - >-
        sam package
        --template-file ./template.yaml
        --output-template-file ./transformed.yaml
        --s3-bucket "${LAMBDA_ARTIFACTS_BUCKET}"
      - cd -
      # BudgetAlarms
      - cd services/budget-alarms/
      - sam build
      - >-
        sed -i "s/AWS_ENVIRONMENT: qa/AWS_ENVIRONMENT: ${AWS_ENVIRONMENT}/g" ./template.yaml
      - >-
        sam package
        --template-file ./template.yaml
        --output-template-file ./transformed.yaml
        --s3-bucket "${LAMBDA_ARTIFACTS_BUCKET}"
      - cd -
      # CodePipelineBotNotifier
      - cd services/codepipeline-notifier
      - sam build
      - >-
        sam package
        --template-file ./template.yaml
        --output-template-file ./transformed.yaml
        --s3-bucket "${LAMBDA_ARTIFACTS_BUCKET}"
      - cd -
      # # S3ToESForwarder
      - cd services/s3-to-es-forwarder
      - sam build
      - >-
        sam package
        --template-file ./template.yaml
        --output-template-file ./transformed.yaml
        --s3-bucket "${LAMBDA_ARTIFACTS_BUCKET}"
      - cd -
      # # TODO: Add ES


  post_build:
    commands:
      - echo "Completed SOAR service build on `date`"

# Add your artifacts here
artifacts:
  files:
    - ./services/hello-world/transformed.yaml
    - ./services/budget-alarms/transformed.yaml
    - ./services/codepipeline-notifier/transformed.yaml
    # TODO: Add ES
    - ./services/s3-to-es-forwarder/transformed.yaml
