---
AWSTemplateFormatVersion: '2010-09-09'
Description: ECR
Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: mythicalmysfits/service
      Tags:
        - Key: Project
          Value: MythicalMysfits

      # aws ecr set-repository-policy --repository-name mythicalmysfits/service --policy-text file://~/environment/aws-modern-application-workshop/module-2/aws-cli/ecr-policy.json
      RepositoryPolicyText:
        Statement:
        - Sid: AllowPushPull
          Effect: Allow
          Principal:
            AWS:
              !ImportValue MythicalMysfitsCoreStack:MythicalMysfitsServiceCodeBuildServiceRole
          Action:
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:BatchCheckLayerAvailability
          - ecr:PutImage
          - ecr:InitiateLayerUpload
          - ecr:UploadLayerPart
          - ecr:CompleteLayerUpload

