---
AWSTemplateFormatVersion: '2010-09-09'
Description: Module 5 streaming
Parameters:
  LambdaArtifactsBucketName:
    Type: String
Resources:
  # aws codecommit create-repository --repository-name MythicalMysfitsStreamingService-Repository
  StreamingServiceRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MythicalMysfitsStreamingService-Repository

  # aws s3 mb s3://REPLACE_ME_YOUR_BUCKET_NAME/
  LambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref LambdaArtifactsBucketName

Outputs:
  LambdaArtifactsBucket:
    Description: The lambda artifacts bucket
    Value: !Ref LambdaArtifactsBucket
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LambdaArtifactsBucket' ] ]
