---
AWSTemplateFormatVersion: '2010-09-09'
Description: ECR
Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: mythicalmysfits/service
      Tags:
        - Key: Project
          Value: MythicalMysfits
