---
AWSTemplateFormatVersion: '2010-09-09'
Description: Module 1 https://github.com/aws-samples/aws-modern-application-workshop/tree/python/module-1
Parameters:
  BucketName:
    Type: String
Resources:
  MythicalMysfitsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  MythicalMysfitsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MythicalMysfitsBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource: !Sub 'arn:aws:s3:::${BucketName}/*'
      Tags:
        - Key: Component
          Value: MythicalMysfits
