AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s3_to_es

  Sample SAM Template for s3_to_es

Parameters:
  AwsEnvironment:
    Type: String
    AllowedValues:
    - qa
    - prod

Globals:
  Function:
    Timeout: 3

Resources:
  ###########################################
  # CLOUDTRAIL for monitoring API calls
  ###########################################
  CloudTrailBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AwsEnvironment}-comp9447-team4-cloudtrail"
      # https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-aws-integrations.html
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !GetAtt AllCloudTrailEsForwarder.Arn

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref CloudTrailBucket
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Sid: "AWSLambdaToRead"
            Effect: "Allow"
            Principal: 
              Service: "lambda.amazonaws.com"
            Action: "s3:Get*"
            Resource:
            - !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail"
            - !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail/*"
          - Sid: "AWSCloudTrailAclCheck"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: 
            - !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail"
            - !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail/*"
          - Sid: "AWSCloudTrailWrite"
            Effect: "Allow"
            Principal: 
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource:
            - !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail"
            - !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail/*"
            Condition: 
              StringEquals:
                s3:x-amz-acl: "bucket-owner-full-control"

  AllTrail:
    DependsOn:
    - BucketPolicy
    - CloudTrailBucket
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: all-trail
      IsLogging: true
      S3BucketName: !Sub ${AwsEnvironment}-comp9447-team4-cloudtrail
      S3KeyPrefix: all

  # The lambda that forwards cloudtrail from S3 to ES
  AllCloudTrailEsForwarder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: forwarder/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt AllCloudTrailEsForwarderRole.Arn
      Environment:
        Variables:
          ES_DOMAIN:
            Fn::ImportValue: !Sub "${AwsEnvironment}-es:DomainEndpoint"
          ES_INDEX: "all_cloud_trail"

  AllCloudTrailEsForwarderRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: AllowReadCloudtrail
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:Get*
            - s3:List*
            Resource:
            - !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail"
            - !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail/*"
      - PolicyName: AllowToPost
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - "es:ESHttpPost"
            Resource: "*"
      AssumeRolePolicyDocument: !Sub >-
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "lambda.amazonaws.com"
              },
              "Action": "sts:AssumeRole"
            }
          ]
        }


  S3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AllCloudTrailEsForwarder.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !Sub "arn:aws:s3:::${AwsEnvironment}-comp9447-team4-cloudtrail"


Outputs:
  AllCloudTrailEsForwarder:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AllCloudTrailEsForwarder.Arn
    Export:
      Name: !Sub "${AWS::StackName}:AllCloudTrailEsForwarder"
