AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s3_to_es

  Sample SAM Template for s3_to_es

Parameters:
  AwsEnvironment:
    Type: String
    AllowedValues:
    - qa
    - prod

Globals:
  Function:
    Timeout: 3

Resources:
  AllCloudTrailEsForwarder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: forwarder/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          ES_DOMAIN:
            Fn::ImportValue: !Sub "${AwsEnvironment}-es:DomainEndpoint"
          ES_INDEX: "all_cloud_trail"

  S3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt AllCloudTrailEsForwarder.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn:
        Fn::ImportValue:
          !Sub "${AwsEnvironment}-CloudTrail:CloudTrailBucketArn"

      

Outputs:
  AllCloudTrailEsForwarder:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AllCloudTrailEsForwarder.Arn
    Export:
      Name: !Sub "${AWS::StackName}:AllCloudTrailEsForwarder"
