AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  s3_to_es

  Sample SAM Template for s3_to_es

Globals:
  Function:
    Timeout: 3

Resources:
  AllCloudTrailEsForwarder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: forwarder/
      Handler: app.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          ES_DOMAIN: "https://search-qa-comp9447-team4-es-vtotgxu23zd6ok2sjurrexojqu.us-east-1.es.amazonaws.com"
          ES_INDEX: "all_cloud_trail"


Outputs:
  AllCloudTrailEsForwarder:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AllCloudTrailEsForwarder.Arn
    Export:
      Name: !Sub "${AWS::StackName}:AllCloudTrailEsForwarder"
