Parameters:
  DomainName:
    Type: String
  
  S3Record:
    Type: String

  HostedZoneId:
    Type: String
  
  HostedZoneIdS3:
    Type: String


Description: Deploy ssl and cloudfront with logging to secure the serveless site
Resources:
  #creates a dns host zone 
  #DNS: 
  #    Type: "AWS::Route53::HostedZone"
  #    Properties: 
  #      HostedZoneConfig: 
  #        Comment: 'Route 53 for web app'
  #      Name: !Ref DomainName
  
  #Add a dns for the s3 bucket
  DNSEntries:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub "${DomainName}."
      RecordSets:
        - AliasTarget:
            HostedZoneId: !Ref HostedZoneIdS3
            DNSName: !Ref S3Record
          Name: !Sub "qa.${DomainName}"
          Type: A
  
  #create a ssl cert
  ACMCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: !Sub "*.${DomainName}"
      DomainValidationOptions:
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS 
    DependsOn: DNSEntries